services:
  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis_data:/data

  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql

  rabbitmq:
    image: rabbitmq:3-management

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    restart: always
    ports:
      - '5000:5000'
    depends_on:
      - db
      - redis
      - rabbitmq
    env_file:
      - .env

  devices:
    build:
      context: .
      dockerfile: apps/devices/Dockerfile
    restart: always
    depends_on:
      - db
      - rabbitmq
    env_file:
      - .env

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    restart: always
    ports:
      - '4200:4200'
    depends_on:
      - backend
    env_file:
      - .env

volumes:
  postgres_data:
  redis_data:
