services:
  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis_data:/data

  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_DATABASE}']
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    healthcheck:
      test: rabbitmq-diagnostics -q check_running
      interval: 10s
      timeout: 5s
      retries: 5

  db_migrate:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    environment:
      DB_HOST: db
      POSTGRES_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_DATABASE}
    command: ['yarn', 'db:migrate']
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    restart: always
    ports:
      - '5000:5000'
    depends_on:
      db:
        condition: service_healthy
      db_migrate:
        condition: service_completed_successfully
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    environment:
      DB_HOST: db
      REDIS_HOST: redis
      RABBITMQ_HOST: rabbitmq
      POSTGRES_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_DATABASE}
      REDIS_URL: redis://redis:6379
      RABBITMQ_URL: amqp://rabbitmq:5672
    env_file:
      - .env

  devices:
    build:
      context: .
      dockerfile: apps/devices/Dockerfile
    restart: always
    depends_on:
      db:
        condition: service_healthy
      db_migrate:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_healthy
    environment:
      DB_HOST: db
      RABBITMQ_HOST: rabbitmq
      POSTGRES_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_DATABASE}
      RABBITMQ_URL: amqp://rabbitmq:5672
    env_file:
      - .env

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    restart: always
    ports:
      - '4200:4200'
    depends_on:
      - backend
    env_file:
      - .env

  auxiliary:
    build:
      context: .
      dockerfile: apps/auxiliary/Dockerfile
    restart: always
    ports:
      - '5001:5000'
    depends_on:
      db:
        condition: service_healthy
      db_migrate:
        condition: service_completed_successfully
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    environment:
      DB_HOST: db
      REDIS_HOST: redis
      RABBITMQ_HOST: rabbitmq
      POSTGRES_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_DATABASE}
      RABBITMQ_URL: amqp://rabbitmq:5672
    env_file:
      - .env

volumes:
  postgres_data:
  redis_data:
